version: "3"

services:

  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    volumes:
      - dbdata:/opt/couchdb/data
      - dbconfig:/opt/couchdb/etc
    environment:
      NODENAME: voteinfo01

  node:
    image: "node:8"
    environment:
      - VIRTUAL_HOST=voteinfo.ch
      - LETSENCRYPT_HOST=voteinfo.ch
      - LETSENCRYPT_EMAIL=lukas.huwyler@gmail.com
    volumes:
      - ./:/voteinfo
    working_dir: /voteinfo
    expose:
      - "3000"
    command: "nodemon index.js"

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    volumes_from:
      - "nginx-proxy"

volumes:
  dbdata:
  dbconfig:
  certs:
  vhosts:
  html:
